<?php

namespace ITSS\TicketsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository {

    public function findOneByIdJoinedToClient($id) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT p, c FROM ITSSTicketsBundle:Projet p
            JOIN p.client c
            WHERE c.id = :id'
                        )->setParameter('id', $id);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
