<?php

namespace ITSS\TicketsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
        public function findOneByIdJoinedToUser($id) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT t, u FROM ITSSTicketsBundle:Ticket t
            JOIN t.user u
            WHERE u.id = :id'
                        )->setParameter('id', $id);

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
