imports:
    - { resource: "@ITSSUserBundle/Resources/config/security.yml" }

# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
       
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CONSULTANT:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_CONSULTANT

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: ROLE_SUPER_ADMIN }
        - { path: ^/, role: ROLE_USER }                