<?php

namespace AC\MediaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThemeDuMoisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeDuMoisRepository extends EntityRepository
{
}
